language: cpp
compiler:
  - gcc
  - clang
before_script:
  - cd Debug
script: rake
branches:
  only:
    - master
notifications:
  recipients:
    - romain.goussault@gmail.com
  email:
    on_success: change
    on_failure: always
env:
  - RVM=2.0.0 LANG="en_US.UTF-8"
os:
  - linux
  - osx