language: cpp

compiler:
  - gcc
 
before_install:
 # g++
 - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
 - sudo add-apt-repository -y ppa:boost-latest/ppa;
 - sudo apt-get update -qq

install:
  # g++
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-5; fi
    # g++ 4.8 is needed to build the old releases
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5"; fi
  
  # Boost
  - sudo apt-get install libboost1.54-all-dev

  # Valgrind
  - sudo apt-get install valgrind
  
before_script:
  - $CXX --version
  - echo "CXX="$CXX
  - mkdir obj
  
script: 
  - make
  - ./DeepovTesting 
 # valgrind --leak-check=full --show-reachable=yes --track-origins=yes --error-exitcode=1  ./DeepovTesting exclude:perft
  - cd test/EloRegressionTest/
  - ./eloRegressionTest.sh

 
notifications:
  email:
    recipients:
      - navid.hedjazian@gmail.com
      - romain.goussault@gmail.com
